### PR TITLE
Issue647

### PR DESCRIPTION
**Pull request by SimonAnnetts**
A 'NewAccountAdminNotificationHtmlEmail' template email will be sent to the emails in 'Email addresses (csv) to notify of  new unapproved users' field in Security Settings if:

1) Account Approval is not required or Email Verification is not required
2) Account Approval is not required, but Email Verification is required, in which case we send only once, the first time a valid email verification key is verified. (Users can click the email link many times ;)

### CODE REVIEW

**Comment by CrispinF** [comment]
@SimonAnnetts looks good.
NB this label 'Email addresses (csv) to notify of new unapproved users' becomes misleading with this change, so should be altered to 'Email addresses (csv) to notify of new users'. Agree? Essentially, if there's an email address in this box, it will be notified of any new user. I think that was the intention of the issue. Correct?

**Comment by SimonAnnetts** [comment]
@CrispinF  Yes, it's already been changed to 'Email addresses (csv) to notify of new users and new unapproved users'

**Comment by CrispinF** [comment]
@SimonAnnetts ok - but isn't the "... and new unapproved users" superfluous and a bit lumpy? "... of new users" is nice and simple and means the same thing.

**Comment by CrispinF** [comment]
PS it's bed time ;-)

**Comment by SimonAnnetts** [comment]
done

**Pull request merged**
